local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("qzrl6 hub v0.1", "GrapeTheme")local Tab = Window:NewTab("character tsb")
local Section = Tab:NewSection("characters")Section:NewButton("satiama mixed power", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/Y3uyGSK6"))()print("Clicked")
end)Section:NewButton("hero hunter To suriyu", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/xVicity/BURNED/main/LATEST.lua'))() print("Clicked")
end)Section:NewButton("satitma To KJ!!!", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/983185f7b0f46a55e497cc29b597ce56/raw/0775d1d0f76d2a2c91a471827a54c70c04984af5/saitama%2520to%2520kj")()print("Clicked")
end)Section:NewButton("satitma to gojo ig free ps+ charecter?", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/2aDTHUTA"))()print("Clicked")
end)Section:NewButton("hero hunter to jotaro", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/h8h88/dfgfdvdf/main/eeeee"))()print("Clicked")
end)Section:NewButton("satiama to god combats", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/ajLiiicx"))()print("Clicked")
end)Section:NewButton("a-train no dmg?!?", "ButtonInfo", function()loadstring(game:HttpGet("https://github.com/l0ckerV5/Roblox-Scripts/raw/main/The%20Strongest%20Battlegrounds/Custom%20Character/A-Train"))()print("Clicked")
end)local Section = Tab:NewSection("click F to hide the Ui.")local Tab = Window:NewTab("Hubs")
local Section = Tab:NewSection("credits to the owner of the following scripts")Section:NewButton("fake KJ hub key Tariviste_GJFaZr4TzrErc5Q", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Tariviste/Gojo/main/Source"))()print("Clicked")
end)Section:NewButton("betless hub x keyless [private]", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/betless-hub-x/raw"))()print("Clicked")
end)Section:NewButton("KJ script Hub keyless", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/AlperPro/shhh/main/KJ%20Script.lua"))()print("Clicked")
end)
local Tab = Window:NewTab("troll thing hahaha")
local Section = Tab:NewSection("trolling")Section:NewButton("fe fling", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe./main/Fling%20GUI"))()print("Clicked")
end)Section:NewButton("infinite yield best admin", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))print("Clicked")
end)local Tab = Window:NewTab( "miisc")
local Section = Tab:NewSection("exploits >:)")Section:NewButton("aimbot", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.co/n55gmtpi/raw", true))()print("Clicked")
end)Section:NewButton("esp", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/imLUDk7h"))()print("Clicked")
end)local Tab = Window:NewTab("KJ stuff")
local Section = Tab:NewSection("KJ :D")Section:NewButton("KJ victim animation", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/75zWy13P"))();print("Clicked")
end)Section:NewButton("20 20 20 dropkick tool bad use fake kj hub if want better", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/7JdC3wL1"))()print("Clicked")
end)Section:NewButton("KJ ult only animation", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/Yk7clVVA/raw"))()print("Clicked")
end)Section:NewButton("stoic bomb", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/cKkjRwyh/raw"))()print("Clicked")
end)Section:NewButton("KJ wall combo", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/u3Apil9t/raw"))()print("Clicked")
end)Section:NewButton("20 20 20 dropkick hitter", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/y1JjYVVm/raw"))()print("Clicked")
end)Section:NewButton("five seasons tp", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/XuHUQwIy/raw"))()print("Clicked")
end)Section:NewButton("five seasons", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/hzerkicS/raw"))()print("Clicked")
end)Section:NewButton("KJ wall combo victim [why did i add this]", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/QVhR9YVl/raw"))()print("Clicked")
end)local Section = Tab:NewSection("animations your animation will be buggy after usage.")local Tab = Window:NewTab("misc 2")
local Section = Tab:NewSection("Misc")Section:NewButton("tsb plugin", "ButtonInfo", function()loadstring(game:HttpGet("https://github.com/l0ckerV5/Roblox-Scripts/raw/main/The-Strongest-Battlegrounds/Plugin-v1.20.91"))()print("Clicked")
end)Section:NewButton("keybored mobile", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()print("Clicked")
end)local Tab = Window:NewTab("hubs 2")
local Section = Tab:NewSection("more hubs")Section:NewButton("no name hub", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/NoName-010/AFAS3000/main/Loader"))()print("Clicked")
end)Section:NewButton("glacier Hub", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/xVicity/GLACIER/main/LATEST.lua"))();print("Clicked")
end)Section:NewButton("kadehub V2", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/JayXSama/ray-makk/main/Loader"))()print("Clicked")
end)Section:NewButton("aqua Hub", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/aquarius-hub/raw"))()print("Clicked")
end)Section:NewButton("auto combo hub", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/autocombo/raw"))print("Clicked")
end)Section:NewButton("mod menu hub", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/ayWSdgWE/raw"))()print("Clicked")
end)Section:NewButton("kilobytes hub", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/GPN1foyD/raw"))()print("Clicked")
end)Section:NewButton("tsb animation", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/Mautiku/ehh/main/strong%20guest.lua.txt'))()print("Clicked")
end)Section:NewButton("sussy hub anygame friend made me add", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/f6faebfa0dfc90a00033ed65a77ffb0e/raw/b90967656b575a90a7747a51f81be2114983e4e3/SUSSY%2520HUB")()print("Clicked")
end)local Tab = Window:NewTab("exploits hehe")
local Section = Tab:NewSection("exploit")Section:NewButton("auto block and aimbot", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/2dJgoWsF/raw"))()print("Clicked")
end)Section:NewButton("auto combo", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/XNKwIjUX/raw"))()print("Clicked")
end)Section:NewButton("rizz no dont use this", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/1imK0X8p/raw"))()print("Clicked")
end)Section:NewButton("mod menu", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/ayWSdgWE/raw"))()print("Clicked")
end)Section:NewButton("auto void kill", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/afHQ7oyj/raw"))()print("Clicked")
end)local Tab = Window:NewTab("games other hub")
local Section = Tab:NewSection("other games")Section:NewButton("legends of speed has keysystem :(", "ButtonInfo", function()loadstring(game:HttpGet("https://waza-scripts.vercel.app/script/LegendsOfSpeed"))()print("Clicked")
end)Section:NewButton("blade ball", "ButtonInfo", function()loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/a5945467f3b9388503ca653c0ea49cba.lua"))()print("Clicked")
end)Section:NewButton("BFNF waza80 Keysystem for free premium", "ButtonInfo", function()loadstring(game:HttpGet("https://waza-scripts.vercel.app/script/BasicallyFNF"))()print("Clicked")
end)Section:NewButton("TSB KJ qzrl6 hub", "ButtonInfo", function()local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("qzrl6 hub v0.1", "GrapeTheme")local Tab = Window:NewTab("character tsb")
local Section = Tab:NewSection("characters")Section:NewButton("satiama mixed power", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/Y3uyGSK6"))()print("Clicked")
end)Section:NewButton("hero hunter To suriyu", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/xVicity/BURNED/main/LATEST.lua'))() print("Clicked")
end)Section:NewButton("satitma To KJ!!!", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/983185f7b0f46a55e497cc29b597ce56/raw/0775d1d0f76d2a2c91a471827a54c70c04984af5/saitama%2520to%2520kj")()print("Clicked")
end)Section:NewButton("satitma to gojo ig free ps+ charecter?", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/2aDTHUTA"))()print("Clicked")
end)Section:NewButton("hero hunter to jotaro", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/h8h88/dfgfdvdf/main/eeeee"))()print("Clicked")
end)Section:NewButton("satiama to god combats", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/ajLiiicx"))()print("Clicked")
end)Section:NewButton("a-train no dmg?!?", "ButtonInfo", function()loadstring(game:HttpGet("https://github.com/l0ckerV5/Roblox-Scripts/raw/main/The%20Strongest%20Battlegrounds/Custom%20Character/A-Train"))()print("Clicked")
end)local Section = Tab:NewSection("click F to hide the Ui.")local Tab = Window:NewTab("Hubs")
local Section = Tab:NewSection("credits to the owner of the following scripts")Section:NewButton("fake KJ hub key Tariviste_GJFaZr4TzrErc5Q", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/Tariviste/Gojo/main/Source"))()print("Clicked")
end)Section:NewButton("betless hub x keyless [private]", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/betless-hub-x/raw"))()print("Clicked")
end)Section:NewButton("KJ script Hub keyless", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/AlperPro/shhh/main/KJ%20Script.lua"))()print("Clicked")
end)
local Tab = Window:NewTab("troll thing hahaha")
local Section = Tab:NewSection("trolling")Section:NewButton("fe fling", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/0Ben1/fe./main/Fling%20GUI"))()print("Clicked")
end)Section:NewButton("infinite yield best admin", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))print("Clicked")
end)local Tab = Window:NewTab( "miisc")
local Section = Tab:NewSection("exploits >:)")Section:NewButton("aimbot", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.co/n55gmtpi/raw", true))()print("Clicked")
end)Section:NewButton("esp", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/imLUDk7h"))()print("Clicked")
end)local Tab = Window:NewTab("KJ stuff")
local Section = Tab:NewSection("KJ :D")Section:NewButton("KJ victim animation", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/75zWy13P"))();print("Clicked")
end)Section:NewButton("20 20 20 dropkick tool bad use fake kj hub if want better", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/7JdC3wL1"))()print("Clicked")
end)Section:NewButton("KJ ult only animation", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/Yk7clVVA/raw"))()print("Clicked")
end)Section:NewButton("stoic bomb", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/cKkjRwyh/raw"))()print("Clicked")
end)Section:NewButton("KJ wall combo", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/u3Apil9t/raw"))()print("Clicked")
end)Section:NewButton("20 20 20 dropkick hitter", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/y1JjYVVm/raw"))()print("Clicked")
end)Section:NewButton("five seasons tp", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/XuHUQwIy/raw"))()print("Clicked")
end)Section:NewButton("five seasons", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/hzerkicS/raw"))()print("Clicked")
end)Section:NewButton("KJ wall combo victim [why did i add this]", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/QVhR9YVl/raw"))()print("Clicked")
end)local Section = Tab:NewSection("animations your animation will be buggy after usage.")local Tab = Window:NewTab("misc 2")
local Section = Tab:NewSection("Misc")Section:NewButton("tsb plugin", "ButtonInfo", function()loadstring(game:HttpGet("https://github.com/l0ckerV5/Roblox-Scripts/raw/main/The-Strongest-Battlegrounds/Plugin-v1.20.91"))()print("Clicked")
end)Section:NewButton("keybored mobile", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()print("Clicked")
end)local Tab = Window:NewTab("hubs 2")
local Section = Tab:NewSection("more hubs")Section:NewButton("no name hub", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/NoName-010/AFAS3000/main/Loader"))()print("Clicked")
end)Section:NewButton("glacier Hub", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/xVicity/GLACIER/main/LATEST.lua"))();print("Clicked")
end)Section:NewButton("kadehub V2", "ButtonInfo", function()loadstring(game:HttpGet("https://raw.githubusercontent.com/JayXSama/ray-makk/main/Loader"))()print("Clicked")
end)Section:NewButton("aqua Hub", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/aquarius-hub/raw"))()print("Clicked")
end)Section:NewButton("auto combo hub", "ButtonInfo", function()loadstring(game:HttpGet("https://rentry.org/autocombo/raw"))print("Clicked")
end)Section:NewButton("mod menu hub", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/ayWSdgWE/raw"))()print("Clicked")
end)Section:NewButton("kilobytes hub", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/GPN1foyD/raw"))()print("Clicked")
end)Section:NewButton("tsb animation", "ButtonInfo", function()loadstring(game:HttpGet('https://raw.githubusercontent.com/Mautiku/ehh/main/strong%20guest.lua.txt'))()print("Clicked")
end)Section:NewButton("sussy hub anygame friend made me add", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/f6faebfa0dfc90a00033ed65a77ffb0e/raw/b90967656b575a90a7747a51f81be2114983e4e3/SUSSY%2520HUB")()print("Clicked")
end)local Tab = Window:NewTab("exploits hehe")
local Section = Tab:NewSection("exploit")Section:NewButton("auto block and aimbot", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/2dJgoWsF/raw"))()print("Clicked")
end)Section:NewButton("auto combo", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/XNKwIjUX/raw"))()print("Clicked")
end)Section:NewButton("rizz no dont use this", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/1imK0X8p/raw"))()print("Clicked")
end)Section:NewButton("mod menu", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/ayWSdgWE/raw"))()print("Clicked")
end)Section:NewButton("auto void kill", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/afHQ7oyj/raw"))()print("Clicked")
end)local Tab = Window:NewTab("games other hub")
local Section = Tab:NewSection("other games")Section:NewButton("legends of speed has keysystem :(", "ButtonInfo", function()loadstring(game:HttpGet("https://waza-scripts.vercel.app/script/LegendsOfSpeed"))()print("Clicked")
end)Section:NewButton("blade ball", "ButtonInfo", function()loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/a5945467f3b9388503ca653c0ea49cba.lua"))()print("Clicked")
end)Section:NewButton("BFNF waza80 Keysystem for free premium", "ButtonInfo", function()loadstring(game:HttpGet("https://waza-scripts.vercel.app/script/BasicallyFNF"))()print("Clicked")
end)Section:NewButton("TSB KJ qzrl6 hub", "ButtonInfo", function()
end)
local Section = Tab:NewSection("key:Zenon12345") local Tab = Window:NewTab("character tsb 2")
local Section = Tab:NewSection("character")Section:NewButton("garou to goku", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/sB9fiEFu"))()print("Clicked")
end)Section:NewButton("satitma to goku", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/dB2TgS33"))()print("Clicked")
end)Section:NewButton("satiama to garou", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/d6ebbUvy"))()print("Clicked")
end)Section:NewButton("garou to KJ", "ButtonInfo", function()loadstring(game:HttpGet"https://raw.githubusercontent.com/h8h88/garouxkj/main/kjxgarou")()print("Clicked")
end)Section:NewButton("temu KJ Any Character", "ButtonInfo", function()loadstring(game:HttpGet"https://pastebin.com/raw/nPanvCvx")()print("Clicked")
end)Section:NewButton("any character to gojo no dmg", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/235d0b19abb38b5637164bf865077817/raw/72cb3b7202fc149d33579ff60f9362ef338bd7d7/fe%2520gojo%2520with%2520fe%2520movement%2520and%2520animation%2520(client%2520vfx%2520+%2520sfx)")()print("Clicked")
end)Section:NewButton("satiama to... coconut?", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/Zd5IL1U2/raw"))()print("Clicked")
end)print("Clicked")
end)
local Section = Tab:NewSection("key:Zenon12345") local Tab = Window:NewTab("character tsb 2")
local Section = Tab:NewSection("character")Section:NewButton("garou to goku", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/sB9fiEFu"))()print("Clicked")
end)Section:NewButton("satitma to goku", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/dB2TgS33"))()print("Clicked")
end)Section:NewButton("satiama to garou", "ButtonInfo", function()loadstring(game:HttpGet("https://pastebin.com/raw/d6ebbUvy"))()print("Clicked")
end)Section:NewButton("garou to KJ", "ButtonInfo", function()loadstring(game:HttpGet"https://raw.githubusercontent.com/h8h88/garouxkj/main/kjxgarou")()print("Clicked")
end)Section:NewButton("temu KJ Any Character", "ButtonInfo", function()loadstring(game:HttpGet"https://pastebin.com/raw/nPanvCvx")()print("Clicked")
end)Section:NewButton("any character to gojo no dmg", "ButtonInfo", function()loadstring(game:HttpGet"https://gist.githubusercontent.com/kjremaker/235d0b19abb38b5637164bf865077817/raw/72cb3b7202fc149d33579ff60f9362ef338bd7d7/fe%2520gojo%2520with%2520fe%2520movement%2520and%2520animation%2520(client%2520vfx%2520+%2520sfx)")()print("Clicked")
end)Section:NewButton("satiama to... coconut?", "ButtonInfo", function()loadstring(game:HttpGet("https://pastefy.app/Zd5IL1U2/raw"))()print("Clicked")
end)